vich_uploader:
    db_driver: orm

    mappings:
        image_cell:
            uri_prefix: /upload/banque-dimages
            upload_destination: '%kernel.project_dir%/public/upload/banque-dimages'
